/** @type {import("ts-jest/dist/types").InitialOptionsTsJest} */
module.exports = {
  preset: "ts-jest",
  testEnvironment: "node",
  roots: ["src"],
  collectCoverageFrom: ["**/*.ts"],
  coveragePathIgnorePatterns: [
    "<rootDir>/.*/index.ts",
    "<rootDir>/test",
    "<rootDir>/src/CommandOptions.ts",
    "<rootDir>/src/KeyCodeCommand.ts",
    "<rootDir>/src/KeystrokeCommand.ts",
    "<rootDir>/src/ScreenReader.ts",
    "<rootDir>/src/macOS/Applications.ts",
    "<rootDir>/src/macOS/KeyCodes.ts",
    "<rootDir>/src/macOS/KeyCodeCommand.ts",
    "<rootDir>/src/macOS/KeystrokeCommand.ts",
    "<rootDir>/src/macOS/Modifiers.ts",
    "<rootDir>/src/macOS/VoiceOver/ClickButton.ts",
    "<rootDir>/src/macOS/VoiceOver/ClickCount.ts",
    "<rootDir>/src/macOS/VoiceOver/CommanderCommands.ts",
    "<rootDir>/src/macOS/VoiceOver/Containments.ts",
    "<rootDir>/src/macOS/VoiceOver/Directions.ts",
    "<rootDir>/src/macOS/VoiceOver/generateClass.ts",
    "<rootDir>/src/macOS/VoiceOver/keyCodeCommands.ts",
    "<rootDir>/src/macOS/VoiceOver/Places.ts",
    "<rootDir>/src/macOS/VoiceOver/VoiceOver.ts",
    "<rootDir>/src/windows",
  ],
};
