/**
 * Default applications available on MacOS.
 */
export enum Applications {
  AppleScriptUtility = "AppleScript Utility",
  AutomatorApplicationStub = "Automator Application Stub",
  Automator = "Automator",
  BluetoothFileExchange = "Bluetooth File Exchange",
  Calendar = "Calendar",
  Console = "Console",
  Contacts = "Contacts",
  DatabaseEvents = "Database Events",
  DigitalHubScripting = "Digital Hub Scripting",
  Finder = "Finder",
  FolderActionsSetup = "Folder Actions Setup",
  FolderActionsDispatcher = "FolderActionsDispatcher",
  FontBook = "Font Book",
  GarageBand = "GarageBand",
  ImageEvents = "Image Events",
  IMovie = "iMovie",
  KeyboardAccessAgent = "KeyboardAccessAgent",
  Keynote = "Keynote",
  Mail = "Mail",
  Messages = "Messages",
  Music = "Music",
  Notes = "Notes",
  Numbers = "Numbers",
  Pages = "Pages",
  PhotoLibraryMigrationUtility = "Photo Library Migration Utility",
  Photos = "Photos",
  Preview = "Preview",
  QuickTimePlayer = "QuickTime Player",
  Reminders = "Reminders",
  Safari = "Safari",
  ScreenSharing = "Screen Sharing",
  ScriptEditor = "Script Editor",
  ShortcutEvents = "Shortcuts Events",
  Shortcuts = "Shortcuts",
  SystemEvents = "System Events",
  SystemInformation = "System Information",
  SystemPreferences = "System Preferences",
  Terminal = "Terminal",
  textEdit = "Text Edit",
  Tv = "TV",
  VoiceOver = "VoiceOver",
}
