/**
 * Default applications available on MacOS.
 */
export enum Applications {
  APPLESCRIPT_UTILITY = "AppleScript Utility",
  AUTOMATOR_APPLICATION_STUB = "Automator Application Stub",
  AUTOMATOR = "Automator",
  BLUETOOTH_FILE_EXCHANGE = "Bluetooth File Exchange",
  CALENDAR = "Calendar",
  CONSOLE = "Console",
  CONTACTS = "Contacts",
  DATABASE_EVENTS = "Database Events",
  DIGITAL_HUB_SCRIPTING = "Digital Hub Scripting",
  FINDER = "Finder",
  FOLDER_ACTIONS_SETUP = "Folder Actions Setup",
  FOLDER_ACTIONS_DISPATCHER = "FolderActionsDispatcher",
  FONT_BOOK = "Font Book",
  GARAGE_BAND = "GarageBand",
  IMAGE_EVENTS = "Image Events",
  IMOVIE = "iMovie",
  KEYBOARD_ACCESS_AGENT = "KeyboardAccessAgent",
  KEYNOTE = "Keynote",
  MAIL = "Mail",
  MESSAGES = "Messages",
  MUSIC = "Music",
  NOTES = "Notes",
  NUMBERS = "Numbers",
  PAGES = "Pages",
  PHOTO_LIBRARY_MIGRATION_UTILITY = "Photo Library Migration Utility",
  PHOTOS = "Photos",
  PREVIEW = "Preview",
  QUICK_TIME_PLAYER = "QuickTime Player",
  REMINDERS = "Reminders",
  SAFARI = "Safari",
  SCREEN_SHARING = "Screen Sharing",
  SCRIPT_EDITOR = "Script Editor",
  SHORTCUTS_EVENTS = "Shortcuts Events",
  SHORTCUTS = "Shortcuts",
  SYSTEM_EVENTS = "System Events",
  SYSTEM_INFORMATION = "System Information",
  SYSTEM_PREFERENCES = "System Preferences",
  TERMINAL = "Terminal",
  TEXT_EDIT = "Text Edit",
  TV = "TV",
  VOICE_OVER = "VoiceOver",
}
