#!/usr/bin/env node

import fs from "node:fs";
import readline from "node:readline";

const logFile = "/tmp/guidepup-orca-speech.log";

function log(text) {
  fs.appendFileSync(logFile, `${text}\n`);
}

function send(text) {
  process.stdout.write(`${text}\n`);
}

const input = readline.createInterface({
  input: process.stdin,
  crlfDelay: Infinity,
});

const iterator = input[Symbol.asyncIterator]();

async function receiveData() {
  const lines = [];

  while (true) {
    const { value: line, done } = await iterator.next();

    if (done) {
      return null;
    }

    if (line === ".") {
      break;
    }

    lines.push(line === ".." ? "." : line);
  }

  return lines.join("\n");
}

while (true) {
  const { value: line, done } = await iterator.next();

  if (done) {
    break;
  }

  if (line === "INIT") {
    send("299 OK LOADED");
  } else if (line === "AUDIO") {
    send("207 OK RECEIVING AUDIO SETTINGS");

    const data = await receiveData();

    if (data === null) {
      break;
    }

    send("203 OK AUDIO SETTINGS RECEIVED");
  } else if (line === "LOGLEVEL") {
    send("200 OK RECEIVING LOGLEVEL");

    const data = await receiveData();

    if (data === null) {
      break;
    }

    send("200 OK");
  } else if (line === "LIST VOICES") {
    send("200 OK");
  } else if (line === "SET") {
    send("203 OK RECEIVING SETTINGS");

    const data = await receiveData();

    if (data === null) {
      break;
    }

    send("203 OK SETTINGS RECEIVED");
  } else if (line === "SPEAK") {
    send("202 OK SEND DATA");

    const data = await receiveData();

    if (data === null) {
      break;
    }

    log(`SPEECH: ${data}`);

    send("200 OK SPEAKING");
    send("701 BEGIN");
    send("702 END");
  } else if (line === "STOP") {
    send("703 STOP");
  } else if (line === "PAUSE") {
    send("704 PAUSE");
  } else if (line === "CANCEL") {
    send("703 STOP");
  } else if (line === "QUIT" || line === "END") {
    send("210 OK QUIT");
    break;
  } else {
    send("200 OK");
  }
}
