name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Enable VoiceOver Automation
        uses: guidepup/setup-action@0.21.0

      # Uncomment and add your steps for your Guidepup tests here
      # - name: Install Dependencies
      #   run: npm ci --no-audit --no-fund --no-progress
      # - name: VoiceOver Test
      #   run: npm run test
