name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-14]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - name: Enable VoiceOver Automation
        uses: guidepup/setup-action@0.19.0

      # Uncomment and add your steps for your Guidepup tests here
      # - name: Install Dependencies
      #   run: yarn install --frozen-lockfile
      # - name: VoiceOver Test
      #   run: yarn test
