name: Test NVDA

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: choco install nvda
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn --cwd=./examples/playwright-nvda install --frozen-lockfile
      - run: yarn --cwd=./examples/playwright-nvda test
