name: Playwright Orca

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  playwright-orca:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, ubuntu-26.04]
        browser: [chromium, firefox]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      # TODO: all installation handled by @guidepup/setup
      - run: |
          sudo apt update
          sudo apt install orca
      # TODO: update @guidepup/setup to support linux + orca
      # - run: npx -y @guidepup/setup@0.24.1 setup --ci
      - run: npm ci --no-audit --no-fund --no-progress
      - run: npm ci --prefix ./examples/playwright-orca --no-audit --no-fund --no-progress
      - run: npm --prefix ./examples/playwright-orca rebuild ffmpeg-static --ignore-scripts=false
      - run: npm --prefix ./examples/playwright-orca run browsers
      # TODO: update @guidepup/setup to support linux + orca
      # - run: npx -y @guidepup/setup@0.24.1 install
      - run: npm --prefix ./examples/playwright-orca run test:${{ matrix.browser }}
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: artifacts-${{ matrix.os }}-${{ matrix.browser }}
          path: |
            **/test-results/**/*
            **/recordings/**/*
