name: Playwright Orca

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  playwright-orca:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-26.04]
        browser: [firefox]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: npx -y --min-release-age=0 @guidepup/setup@0.25.1 setup --ci
      - run: npm ci --no-audit --no-fund --no-progress
      - run: npm ci --prefix ./examples/playwright-orca --no-audit --no-fund --no-progress
      - run: npm --prefix ./examples/playwright-orca rebuild ffmpeg-static --ignore-scripts=false
      - run: npm --prefix ./examples/playwright-orca run browsers
      - run: npx -y --min-release-age=0 @guidepup/setup@0.25.1 install
      - run: |
          # TODO: migrate all process running / validation / setup to Guidepup runtime

          pulseaudio \
            --start \
            --exit-idle-time=-1 \
            --log-target=stderr >/dev/null 2>&1 &

          export SPEECHD_DIR=/tmp/guidepup-speechd

          ls -laR /home/runner/.cache/guidepup/orca/7/0.2.0-50.2/extracted

          cp -r /home/runner/.cache/guidepup/orca/7/0.2.0-50.2/extracted/speechd/. "${SPEECHD_DIR}/"

          mkdir -p \
            "${SPEECHD_DIR}/logs" \
            "${SPEECHD_DIR}/run"

          ls -laR ${SPEECHD_DIR}

          Xvfb :99 >/dev/null 2>&1 &
          export DISPLAY=:99

          sleep 1

          eval "$(dbus-launch --sh-syntax --exit-with-session)"

          sleep 5

          /usr/libexec/at-spi-bus-launcher --launch-immediately >/dev/null 2>&1 &

          sleep 5

          DEBUG=guidepup:* npm --prefix ./examples/playwright-orca run test:${{ matrix.browser }} || true
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: artifacts-${{ matrix.os }}-${{ matrix.browser }}
          path: |
            **/test-results/**/*
            **/recordings/**/*
